[package]
name = "dcel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.9.0"
ghost-cell = "0.2.3"
rand = "0.8.5"
stl_io = "0.7.0"
typed-arena = "2.0.2"
